export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_MY_INFO = 'SET_MY_INFO'
export const DESTROY_ACCESS_TOKEN = 'DESTROY_ACCESS_TOKEN'
export const DESTROY_MY_INFO = 'DESTROY_MY_INFO'

export const FETCH_POST_LIST = 'FETCH_POST_LIST'
export const FETCH_POST = 'FETCH_POST'

export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
